server:
  port: ${hp.serverPort}
debug: true
logging:
  level:
    com.hp.placeholder.mapper: debug
  file:
    name: E:\workspace\placeholder\log\hp.log
hp:
  value: value
  placeholder: ?{hp.place}
hpp:
  userName: hanpeng
  passWord: 102621